name: Tests

on: [push]

jobs:
  run:
    runs-on: ["macos-latest"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
      - uses: actions/setp-node@v1
          with:
            node-version: "16"
      - name: Install dependencies
      - run: npm install
      - name: Run Jest tests
        run: npm run test
